"""added reset token table to store user reset tokens

Revision ID: c1a01d623ade
Revises: ab5360a0f3c0
Create Date: 2024-03-09 18:16:48.870081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a01d623ade'
down_revision = 'ab5360a0f3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_fullname', ['fullname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_fullname', type_='unique')

    # ### end Alembic commands ###
